export const TODO_LOAD_REQUEST = "TODO_LOAD_REQUEST";
export const TODO_LOAD_SUCCESS = "TODO_LOAD_SUCCESS";
export const TODO_LOAD_FAIL = "TODO_LOAD_FAIL";
export const TODO_LOAD_RESET = "TODO_LOAD_RESET";


export const TODO_LOAD_SINGLE_REQUEST = "TODO_LOAD_SINGLE_REQUEST";
export const TODO_LOAD_SINGLE_SUCCESS = "TODO_LOAD_SINGLE_SUCCESS";
export const TODO_LOAD_SINGLE_FAIL = "TODO_LOAD_SINGLE_FAIL";
export const TODO_LOAD_SINGLE_RESET = "TODO_LOAD_SINGLE_RESET";

export const CREATE_TODO_REQUEST = "CREATE_TODO_REQUEST";
export const CREATE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const CREATE_TODO_FAIL = "CREATE_TODO_FAIL";
export const CREATE_TODO_RESET = "CREATE_TODO_RESET";

export const DELETE_TODO_REQUEST = "CREATE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS = "CREATE_TODO_SUCCESS";
export const DELETE_TODO_FAIL = "CREATE_TODO_FAIL";
export const DELETE_TODO_RESET = "CREATE_TODO_RESET";

export const UPDATE_TODO_REQUEST = "UPDATE_TODO_REQUEST";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_FAIL = "UPDATE_TODO_FAIL";
export const UPDATE_TODO_RESET = "UPDATE_TODO_RESET";